<div class="row">
    <div class="col-sm-5">
        <div class="panel panel-info">
            <div class="panel-heading"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?php echo get_phrase('Add Sale'); ?></div>
            <div class="panel-body table-responsive">
                <?php echo form_open('admin/create_sale', array('class' => 'form-horizontal form-groups-bordered validate')); ?>
                <!----CREATION FORM STARTS---->
                <div class="form-group">
                    <label class="col-md-12" for="receipt-no"><?php echo get_phrase('Receipt No. (Autogenerated)'); ?></label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="receipt_no" id="receipt-no" value="<?php echo $receipt_no; ?>" placeholder="<?php echo $receipt_no; ?>" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="example-text"><?php echo get_phrase('Product'); ?></label>
                    <div class="col-sm-12">
                        <select class="form-control" name="product_id" id="product" required>
                            <option value="">Select Product Type</option>
                            <?php foreach ($products as $product): ?>
                                <option value="<?php echo $product->id; ?>"><?php echo $product->product_name; ?> (<?php echo $product->flavour; ?>) <?php echo $product->volume_size; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="stockqty"><?php echo get_phrase('Stock Quantity'); ?></label>
                    <div class="col-sm-12">
                        <input type="number" min="1" max="1" class="form-control" name="stock_qty" id="stockqty" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="example-text"><?php echo get_phrase('Date'); ?></label>
                    <div class="col-sm-12">
                        <input type="date" class="form-control" name="date" value="<?php echo date('Y-m-d'); ?>" required/>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-info btn-sm btn-block btn-rounded"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?php echo get_phrase('Sale'); ?></button>
                </div>
                <?php echo form_close(); ?>
            </div>
        </div>
    </div>
    <!----CREATION FORM ENDS-->

    <div class="col-sm-7">
        <div class="panel panel-info">
            <div class="panel-heading"><i
                        class="fa fa-list"></i>&nbsp;&nbsp;<?php echo get_phrase('Available Stock'); ?></div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body table-responsive">
                    <table id="example23" class="display nowrap" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>
                                <div>#</div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('name'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('type'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('flavour'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('volume'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('stock'); ?></div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $count = 1;
                        foreach ($products as $product):
                            ?>
                            <tr>
                                <td><?php echo $count++; ?></td>
                                <td><?php echo $product->product_name; ?></td>
                                <td><?php echo $product->product_type; ?></td>
                                <td><?php echo $product->flavour; ?></td>
                                <td><?php echo $product->volume_size; ?></td>
                                <td><?php echo $product->stock_qty; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!----TABLE LISTING ENDS--->
<script>
    const productDropdown = document.getElementById("product");
    productDropdown.addEventListener("change", fetchCurrentStock);
    function fetchCurrentStock() {
        const selectedProductId = this.value; // Get the selected product ID from the dropdown
        // Send an AJAX request to the server
        // Replace 'fetch_stock_url' with the actual URL that handles the stock retrieval
        fetch(`<?php echo base_url("admin/fetch_stock"); ?>/${selectedProductId}`)
            .then(response => response.json())
            .then(data => {
                const currentStock = data.stock; // Assuming the server response contains the stock value
                // Set the max attribute of the number input field
                const stockInput = document.getElementById("stockqty"); // Replace 'stockInput' with the actual input ID
                stockInput.max = currentStock;
            })
            .catch(error => {
                console.log("Error fetching stock:", error);
            });
    }

</script>
