<div class="row">
    <div class="col-sm-5">
        <div class="panel panel-info">
            <div class="panel-heading"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?php echo get_phrase('Record Delivery'); ?></div>
            <div class="panel-body table-responsive">
                <?php echo form_open('admin/create_delivery', array('class' => 'form-horizontal form-groups-bordered validate')); ?>
                <!----CREATION FORM STARTS---->
                <div class="form-group">
                    <label class="col-md-12" for="invoice-no"><?php echo get_phrase('Delivery/ Tracking No. (Autogenerated)'); ?></label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="invoice_no" id="invoice-no" value="<?php echo $invoice_no; ?>" placeholder="<?php echo $invoice_no; ?>" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="example-text"><?php echo get_phrase('Product'); ?></label>
                    <div class="col-sm-12">
                        <select class="form-control" name="product_id" id="product" required>
                            <option value="">Select Product Type</option>
                            <?php foreach ($products as $product): ?>
                                <option value="<?php echo $product->id; ?>"><?php echo $product->product_name; ?> (<?php echo $product->flavour; ?>) <?php echo $product->volume_size; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="example-text"><?php echo get_phrase('Vehicle'); ?></label>
                    <div class="col-sm-12">
                        <select class="form-control" name="vehicle" id="vehicle" required>
                            <?php foreach ($vehicles as $vehicle): ?>
                                <option value="<?php echo $vehicle->vehicle_id; ?>"><?php echo $vehicle->vehicle_number; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="stock-qty"><?php echo get_phrase('Stock Quantity'); ?></label>
                    <div class="col-sm-12">
                        <input type="number" class="form-control" name="stock_qty" id="stock-qty" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12" for="example-text"><?php echo get_phrase('Date'); ?></label>
                    <div class="col-sm-12">
                        <input type="date" class="form-control" name="date" value="<?php echo date('Y-m-d'); ?>" required/>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-info btn-sm btn-block btn-rounded"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?php echo get_phrase('Record Delivery'); ?></button>
                </div>
                <?php echo form_close(); ?>
            </div>
        </div>
    </div>
    <!----CREATION FORM ENDS-->

    <div class="col-sm-7">
        <div class="panel panel-info">
            <div class="panel-heading"><i
                        class="fa fa-list"></i>&nbsp;&nbsp;<?php echo get_phrase('Available Stock'); ?></div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body table-responsive">
                    <table id="example23" class="display nowrap" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>
                                <div>#</div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('name'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('type'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('flavour'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('volume'); ?></div>
                            </th>
                            <th>
                                <div><?php echo get_phrase('stock'); ?></div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $count = 1;
                        foreach ($products as $product):
                            ?>
                            <tr>
                                <td><?php echo $count++; ?></td>
                                <td><?php echo $product->product_name; ?></td>
                                <td><?php echo $product->product_type; ?></td>
                                <td><?php echo $product->flavour; ?></td>
                                <td><?php echo $product->volume_size; ?></td>
                                <td><?php echo $product->stock_qty; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!----TABLE LISTING ENDS--->
